#!/usr/bin/env bash

function say-hello {
  local pth_main="$1"; shift

  cat <<__EOF
(ns hello.core
  (:require [cljs.nodejs :as nodejs]))

(nodejs/enable-util-print!)
__EOF

  cat "$pth_main"

  cat <<__EOF
(set! *main-cli-fn* -main)
__EOF
}

function main {
  local shome="${_cljs_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  local pth_cljs="$1"; shift
  local pth_compiled="$1"; shift

  mkdir -p "$shome/src/hello"
  say-hello "$pth_cljs" > "$shome/src/hello/core.cljs"

  rm -rf "$shome/out"
  (cd "$shome" && java -cp "$shome/vendor/src/cljs.jar:src" clojure.main "$shome/build.clj")
  mv "$shome/out/main.js" "$pth_compiled"
  chmod 755 "$pth_compiled"
}

source sub "$BASH_SOURCE" "$@"
