#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_app="${1:-}"

  block compile npm

  local url_cljs='https://github.com/clojure/clojurescript/releases/download/r1.9.293/cljs.jar'
  local fnm_cljs='cljs-1.9.293.jar'

  cache curl "$fnm_cljs" "$url_cljs"

  mkdir -p "$shome/vendor/src"
  rsync -ia "${BASEBOX_CACHE}/curl/$fnm_cljs" "$shome/vendor/src/"
  ln -nfs "$fnm_cljs" "$shome/vendor/src/cljs.jar"
}

bootstrap "$@"
