#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -e "$shome/vendor/src/cljs.jar" ]]; then
    return 0
  fi

  return 1
}

bootstrap "$@"
