#!/usr/bin/env bash

function server {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_app="${1:-}"

  if [[ -z "$nm_app" ]]; then
    echo "ERROR: specify an app to run" 1>&2
    return 1
  fi

  case "${1:-}" in
    default)
        exec node "$shome/out/${nm_app}/main.js"
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

server "$@"
